# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: /blog
url: https://since1991hy.github.io
date_format: "ordinal"
title: 秋意浓
subtitle: "把生活过成段子, 把代码写成诗"
description: "赵一鹏的个人博客"
keywords: 秋意浓, Yipeng Zhao, since1991, since1991hy
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/since1991hy/blog
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yipeng Zhao
organization: sict, Inc.
organization_url: http://www.sict.ac.cn/
location: 沈阳, 辽宁
email: since1991hy@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
#用于自动生成文章摘要
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: since1991hy
#douban_username: 
#facebook_username: 
#weibo_username: 
#zhihu_username: 
#twitter_username: 

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_shortname: since1991hy
#disqus 被"墙"了, 故不再使用
#disqus_username: null

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
baidu:
    uuid: fa0df33bb7247c4c8c70d4150609587d

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Design Patterns, MySql, SSH]
#skill_mobile_app_keywords: [Android, Reverse Engineering]
#skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
